export default {
  forward: require("../assets/images/logo.png"),
  ic_google: require("../assets/images/ic_google.png"),
  ic_fb: require("../assets/images/ic_facebook.png"),
  ic_apple: require("../assets/images/ic_apple.png"),
  ic_1: require("../assets/images/ic_1.png"),
  ic_back_arrow: require("../assets/images/ic_back_arrow.png"),
  grey_tick: require("../assets/images/ic_grey_tick.png"),
  blue_tick: require("../assets/images/ic_blue_tick.png"),
  googlelogo: require("../assets/images/ic_google.png"),
  applelogo: require("../assets/images/ic_apple.png"),
  homebanner1: require("../assets/images/homeimg1.png"),
  homebanner2: require("../assets/images/homeimg2.png"),
  homebanner3: require("../assets/images/homeimg3.png"),
  forwardicon: require("../assets/images/ic_home_icon.png"),
  location: require("../assets/images/ic_loc.png"),
  threedot: require("../assets/images/ic_dots.png"),
  direction: require("../assets/images/ic_direction.png"),
  cross: require("../assets/images/ic_cross.png"),
  user: require("../assets/images/ic_user.png"),
  key: require("../assets/images/ic_key.png"),
  signout: require("../assets/images/ic_logout.png"),
  editprofile: {
    uri: "https://cdn.dribbble.com/users/5534/screenshots/14230133/profile_4x.jpg",
  },
  plus: require("../assets/images/ic_plus.png"),
  home: require("../assets/images/ic_home.png"),
  search: require("../assets/images/ic_srch.png"),
  upload: require("../assets/images/ic_add.png"),
  notifications: require("../assets/images/ic_notify.png"),
  profile: require("../assets/images/ic_user.png"),
  unchecked: require("../assets/images/unchecked.png"),
  checkbox: require("../assets/images/checkbox.png")
};
