export default {
  get_started: "Get Started",
  By_clicking_log_in:
    "By clicking “Log In”, you agree with our ",
  Learn_how: 'Learn how we process our data in our ',
  or: "or",
  login_ph_no: "Login with phone number",
  login_google: "Login with Google",
  login_facebook: "Login with Facebook",
  login_apple: "Login with Apple",
  new_here: "New here?",
  sign_up: "Sign Up",
  Hendrerit: " Hendrerit vulputate sem",
  Aeneantxt:
    "Aenean et convallis nulla. Donec in efficitur nisi, et vestibulum quamaenean.",
  Welcome: "Welcome!",
  we_are_happy: "We are happy to see. You can login to continue.",
  use_otp: "Use OTP",
  forgot_password: "Forget password",
  countrycode: "+91",
  mobileno: "Mobile number",
  login: "Login",
  password: "Password",
  show: "Show",
  create_new_account: "Create new account",
  create_an_acc_so_u_can_continue: "Create an account so you can continue.",
  firstname: "Firstname",
  lastname: "Lastname",
  email: "Email",
  next: "Next",
  set_password: "Set password",
  create_secure_unique_password: "Create secure and unique password.",
  confirm_password: "Confirm password",
  enter_otp: "Enter the 4-digit code sent to you at 875 364 8947",
  edit_mobile_no: "Edit my mobile number",
  resend_code: "Resend code ",
  sector55: "Sector 55,Chandigarh",
  sector22: "Sector 22,Chandigarh",
  sector48: "Sector 48,Chandigarh",
  sector26: "Sector 26,Chandigarh",
  sector40: "Sector 40,Chandigarh",
  sector67: "Sector 67,Mohali",
  device_off: "Device location is off",
  turning_on_device_location:
    "Turning on device location will ensure accurate road alerts.",
  enter_location: "Enter location manually",
  suggestions: "Suggestions",
  select_and_proceed: "SELECT & PROCEED",
  turn_on: "TURN ON",
  or: "or",
  inputfieldcolor: "#A5A5A5",
  verify: "VERIFY",
  personaddress: "Sector 28D, Chandigarh",
  lorem:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Etiam in turpis luctus.",
  time: "1 hr ago",
  comments: "Comments 1,224",
  likes: "Like 44,678",
  editprofile: "Edit Profile",
  changepass: "Change Password",
  signout: "Signout",
  viewmap: "VIEW MAP",
  editprofile: "Edit Profile",
  savechanges: "SAVE CHANGES",
  save: "SAVE",
  no: "966 559 659 5695",
  addinfo: "Add info",
  post: "POST",
  show: 'Show'
};
